# Generated by Django 6.1 on 2026-08-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo_categoria', models.CharField(choices=[('Laboral', 'Laboral'), ('Educativa', 'Educativa'), ('Comercial', 'Comercial'), ('Otra', 'Otra')], max_length=50, verbose_name='Tipo de categoría')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado (Activa/Inactiva)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
