# Generated by Django 6.1 on 2026-08-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaVacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150)),
                ('sector', models.CharField(max_length=100)),
                ('experiencia', models.CharField(max_length=100)),
                ('modalidad', models.CharField(max_length=50)),
                ('ciudad_region', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.CharField(max_length=150)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ofertas_vacantes',
            },
        ),
    ]
