# Generated by Django 6.1 on 2026-08-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HojaVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('educacion', models.TextField()),
                ('experiencia_laboral', models.TextField()),
                ('idiomas', models.CharField(max_length=200)),
                ('antecedentes_penales', models.TextField()),
                ('habilidades', models.TextField()),
            ],
        ),
    ]
