# Generated by Django 6.1 on 2026-08-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empleate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojavida',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='soporte_educacion',
            field=models.FileField(blank=True, null=True, upload_to='soportes/educacion/'),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='soporte_experiencia',
            field=models.FileField(blank=True, null=True, upload_to='soportes/experiencia/'),
        ),
    ]
