# Generated by Django 6.1 on 2026-08-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_empleate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofertavacante',
            old_name='ciudad_region',
            new_name='categoria',
        ),
        migrations.RemoveField(
            model_name='ofertavacante',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='ofertavacante',
            name='modalidad',
        ),
        migrations.RemoveField(
            model_name='ofertavacante',
            name='sector',
        ),
    ]
