# Generated by Django 6.1 on 2026-09-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_postulacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hojadevida',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='hojadevida',
            name='titulo_profesional',
        ),
    ]
