# Generated by Django 6.1 on 2026-08-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_postulante', models.IntegerField(verbose_name='ID del Postulante')),
                ('id_entrevistador', models.IntegerField(verbose_name='ID del Entrevistador')),
                ('comentarios_entrevistador', models.TextField(blank=True, null=True, verbose_name='Comentarios de la Entrevista')),
                ('puntaje_entrevista', models.IntegerField(blank=True, null=True, verbose_name='Puntaje Obtenido')),
                ('resultado_test_diagnostico', models.TextField(blank=True, null=True, verbose_name='Resultados del Test')),
                ('nivel_inicial_detectado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nivel Inicial Detectado')),
                ('tips_entrenamiento', models.TextField(blank=True, null=True, verbose_name='Tips de Entrenamiento')),
                ('recomendaciones_mejora', models.TextField(blank=True, null=True, verbose_name='Recomendaciones de Mejora')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
        ),
    ]
